services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"
      - "5341:5341"
    volumes:
      - seq-data:/data

volumes:
  seq-data:
